name: Test and Build

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    
  workflow_dispatch:

jobs:
  build:
    name: Generatee Debug APK
    needs: [ unit_tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Debug APK
        run: ./gradlew --warning-mode all assembleDebug

      - uses: actions/upload-artifact@master
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk